# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'authentication method',
                'verbose_name_plural': 'authentication methods',
            },
        ),
        migrations.CreateModel(
            name='ProductLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'product location',
                'verbose_name_plural': 'product locations',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=200, verbose_name='Product|color'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Product|purchase year'),
        ),
        migrations.AddField(
            model_name='product',
            name='serial_code',
            field=models.CharField(blank=True, max_length=200, verbose_name='Product|serial code'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='authentication_method',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.AuthenticationMethod', verbose_name='Product|authentication method'),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.ProductLocation', verbose_name='Product|location'),
        ),
    ]
