# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 05:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170728_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Address|fullname')),
                ('phone_number', models.CharField(max_length=30, verbose_name='phone number')),
                ('country', models.CharField(choices=[('US', 'United State'), ('CA', 'Canada')], max_length=3, verbose_name='country')),
                ('street_address', models.CharField(max_length=200, verbose_name='street address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('province', models.CharField(max_length=100, verbose_name='Address|province')),
                ('zip_code', models.CharField(max_length=20, verbose_name='ZIP code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
        ),
    ]
