# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 08:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20170729_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('paypal', 'PayPal'), ('credit-card', 'credit card'), ('alipay', 'Alipay')], max_length=20, verbose_name='PaymentMethod|method')),
                ('info', jsonfield.fields.JSONField(blank=True, default={}, verbose_name='PaymentMethod|information')),
                ('secret', jsonfield.fields.JSONField(blank=True, default={}, verbose_name='PaymentMethod|secret information')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'payment method',
                'verbose_name_plural': 'payment methods',
            },
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='contact',
            field=jsonfield.fields.JSONField(blank=True, default={}, verbose_name='UserInfo|contact'),
        ),
    ]
