# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20170714_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'product image', 'verbose_name_plural': 'product images'},
        ),
        migrations.AlterField(
            model_name='category',
            name='super_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='super category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(null=True, upload_to='images/products/', verbose_name='Product|main image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.FloatField(verbose_name='Product|original price'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='images/products/', verbose_name='image'),
        ),
    ]
