# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20170904_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.IntegerField(editable=False, verbose_name='category level'),
        ),
    ]
