# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20170714_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='images/placeholder-120x120.png', upload_to='images/products/', verbose_name='Product|main image'),
        ),
    ]
