# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20170904_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_on_homepage',
            field=models.BooleanField(default=False, verbose_name='Product|show on homepage'),
        ),
    ]
