# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 10:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20170729_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusTransition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happened_dt', models.DateTimeField(auto_now_add=True, verbose_name='happened datetime')),
                ('src_status', models.CharField(choices=[('unpaid', 'OrderStatus|unpaid'), ('paid', 'OrderStatus|paid'), ('shipping', 'OrderStatus|shipping'), ('done', 'OrderStatus|done'), ('canceling', 'OrderStatus|canceling'), ('canceled', 'OrderStatus|canceled'), ('return-requested', 'OrderStatus|return requested'), ('returning', 'OrderStatus|returning'), ('returned', 'OrderStatus|returned')], max_length=20, verbose_name='status')),
                ('dst_status', models.CharField(choices=[('unpaid', 'OrderStatus|unpaid'), ('paid', 'OrderStatus|paid'), ('shipping', 'OrderStatus|shipping'), ('done', 'OrderStatus|done'), ('canceling', 'OrderStatus|canceling'), ('canceled', 'OrderStatus|canceled'), ('return-requested', 'OrderStatus|return requested'), ('returning', 'OrderStatus|returning'), ('returned', 'OrderStatus|returned')], max_length=20, verbose_name='status')),
            ],
            options={
                'verbose_name': 'order status transition',
                'verbose_name_plural': 'order status transitions',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Address|fullname')),
                ('phone_number', models.CharField(max_length=30, verbose_name='phone number')),
                ('country', models.CharField(choices=[('US', 'United State'), ('CA', 'Canada')], max_length=3, verbose_name='Address|country')),
                ('street_address', models.CharField(max_length=200, verbose_name='Address|street address')),
                ('city', models.CharField(max_length=100, verbose_name='Address|city')),
                ('province', models.CharField(max_length=100, verbose_name='Address|province')),
                ('zip_code', models.CharField(max_length=20, verbose_name='Address|ZIP code')),
            ],
            options={
                'verbose_name': 'shipping address',
                'verbose_name_plural': 'shipping addresses',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='from_balance',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='use_balance',
        ),
        migrations.AddField(
            model_name='order',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='express_company',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='express company'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_status',
            field=models.CharField(blank=True, choices=[('unpaid', 'OrderStatus|unpaid'), ('paid', 'OrderStatus|paid'), ('shipping', 'OrderStatus|shipping'), ('done', 'OrderStatus|done'), ('canceling', 'OrderStatus|canceling'), ('canceled', 'OrderStatus|canceled'), ('return-requested', 'OrderStatus|return requested'), ('returning', 'OrderStatus|returning'), ('returned', 'OrderStatus|returned')], max_length=20, null=True, verbose_name='last status'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_express_company',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='return express company'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_tracking_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='return tracking number'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='tracking number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', 'OrderStatus|unpaid'), ('paid', 'OrderStatus|paid'), ('shipping', 'OrderStatus|shipping'), ('done', 'OrderStatus|done'), ('canceling', 'OrderStatus|canceling'), ('canceled', 'OrderStatus|canceled'), ('return-requested', 'OrderStatus|return requested'), ('returning', 'OrderStatus|returning'), ('returned', 'OrderStatus|returned')], default='unpaid', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='published_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Product|published datetime'),
        ),
        migrations.AddField(
            model_name='orderstatustransition',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_transitions', to='shop.Order', verbose_name='order'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='shop.ShippingAddress', verbose_name='shipping address'),
            preserve_default=False,
        ),
    ]
