# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_miscinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscinfo',
            name='promotion',
            field=models.CharField(blank=True, max_length=200, verbose_name='promotion message'),
        ),
    ]
