# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20170730_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='shop.ShippingAddress', verbose_name='shipping address'),
            preserve_default=False,
        ),
    ]
