# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 08:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0008_auto_20170715_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(verbose_name='total strike price')),
                ('status', models.CharField(choices=[('UNPAID', 'OrderStatus|unpaid'), ('PAID', 'OrderStatus|paid'), ('SHIPPING', 'OrderStatus|shipping'), ('DONE', 'OrderStatus|done'), ('CANCELED', 'OrderStatus|canceled')], default='UNPAID', max_length=20, verbose_name='status')),
                ('payment_method', models.CharField(choices=[('BALANCE', 'PaymentMethod|balance'), ('PAYPAL', 'PaymentMethod|paypal'), ('STRIPE', 'PaymentMethod|stripe')], max_length=20, verbose_name='payment method')),
                ('use_balance', models.BooleanField(verbose_name='Order|use balance')),
                ('from_balance', models.FloatField(verbose_name='Order|from balance')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='strike price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.Order', verbose_name='order')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='shop.Product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
            },
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='info', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
