# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20170730_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='shop.Order', verbose_name='order'),
            preserve_default=False,
        ),
    ]
