# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text='Color of the product.', max_length=200, verbose_name='Product|color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the product.', max_length=200, verbose_name='Product|name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, help_text='Size of the product.', max_length=20, verbose_name='Product|size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='style',
            field=models.CharField(blank=True, help_text='Style of the product.', max_length=200, verbose_name='Product|style'),
        ),
    ]
