# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20170730_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatustransition',
            name='dst_status',
            field=models.CharField(choices=[('unpaid', 'OrderStatus|unpaid'), ('paid', 'OrderStatus|paid'), ('shipping', 'OrderStatus|shipping'), ('done', 'OrderStatus|done'), ('canceling', 'OrderStatus|canceling'), ('canceled', 'OrderStatus|canceled'), ('return-requested', 'OrderStatus|return requested'), ('returning', 'OrderStatus|returning'), ('returned', 'OrderStatus|returned')], max_length=20, verbose_name='destination status'),
        ),
        migrations.AlterField(
            model_name='orderstatustransition',
            name='src_status',
            field=models.CharField(choices=[('unpaid', 'OrderStatus|unpaid'), ('paid', 'OrderStatus|paid'), ('shipping', 'OrderStatus|shipping'), ('done', 'OrderStatus|done'), ('canceling', 'OrderStatus|canceling'), ('canceled', 'OrderStatus|canceled'), ('return-requested', 'OrderStatus|return requested'), ('returning', 'OrderStatus|returning'), ('returned', 'OrderStatus|returned')], max_length=20, verbose_name='source status'),
        ),
    ]
