# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20170723_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publish_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Product|publish datetime'),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Product|sold datetime'),
        ),
    ]
