# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20170730_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.FloatField(default=0.0, verbose_name='discount amount'),
        ),
    ]
