# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20170723_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('balance', 'PaymentMethod|balance'), ('paypal', 'PaymentMethod|paypal'), ('stripe', 'PaymentMethod|stripe')], max_length=20, verbose_name='payment method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', 'OrderStatus|unpaid'), ('paid', 'OrderStatus|paid'), ('shipping', 'OrderStatus|shipping'), ('done', 'OrderStatus|done'), ('canceled', 'OrderStatus|canceled')], default='unpaid', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('S', 'ProductCondition|S'), ('A+', 'ProductCondition|A+'), ('A', 'ProductCondition|A'), ('B', 'ProductCondition|B'), ('C', 'ProductCondition|C'), ('D', 'ProductCondition|D')], max_length=2, verbose_name='Product|condition'),
        ),
    ]
