# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='recharged',
            field=models.BooleanField(default=False, verbose_name='Payment|recharged'),
        ),
    ]
