# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20170723_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'attachment',
                'verbose_name_plural': 'attachments',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='attachments',
        ),
        migrations.AddField(
            model_name='product',
            name='attachments',
            field=models.ManyToManyField(related_name='products', to='shop.Attachment', verbose_name='Product|attachments'),
        ),
    ]
