# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_payment_recharged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='authentication_method',
        ),
        migrations.AddField(
            model_name='product',
            name='authentication_methods',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.AuthenticationMethod', verbose_name='Product|authentication methods'),
        ),
    ]
