# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20170723_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publish_dt',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='Product|publish datetime'),
        ),
    ]
