# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20170914_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellrequest',
            name='done_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SellRequest|done datetime'),
        ),
    ]
