# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20170731_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='return_express_company',
        ),
        migrations.RemoveField(
            model_name='order',
            name='return_tracking_number',
        ),
    ]
