# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20170723_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attachments',
            field=models.ManyToManyField(to='shop.Attachment', verbose_name='Product|attachments'),
        ),
        migrations.AlterField(
            model_name='product',
            name='publish_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Product|publish datetime'),
        ),
    ]
