# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20170723_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='products\\placeholder-120x120.png', upload_to='products', verbose_name='Product|main image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products', verbose_name='image'),
        ),
    ]
