# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20170801_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='last_status',
            field=models.CharField(blank=True, choices=[('unpaid', 'OrderStatus|unpaid'), ('paid', 'OrderStatus|paid'), ('cancelling', 'OrderStatus|cancelling'), ('cancelled', 'OrderStatus|cancelled'), ('shipping', 'OrderStatus|shipping'), ('done', 'OrderStatus|done'), ('return-requested', 'OrderStatus|return requested'), ('returning', 'OrderStatus|returning'), ('returned', 'OrderStatus|returned')], max_length=20, null=True, verbose_name='last status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', 'OrderStatus|unpaid'), ('paid', 'OrderStatus|paid'), ('cancelling', 'OrderStatus|cancelling'), ('cancelled', 'OrderStatus|cancelled'), ('shipping', 'OrderStatus|shipping'), ('done', 'OrderStatus|done'), ('return-requested', 'OrderStatus|return requested'), ('returning', 'OrderStatus|returning'), ('returned', 'OrderStatus|returned')], default='unpaid', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='orderstatustransition',
            name='dst_status',
            field=models.CharField(choices=[('unpaid', 'OrderStatus|unpaid'), ('paid', 'OrderStatus|paid'), ('cancelling', 'OrderStatus|cancelling'), ('cancelled', 'OrderStatus|cancelled'), ('shipping', 'OrderStatus|shipping'), ('done', 'OrderStatus|done'), ('return-requested', 'OrderStatus|return requested'), ('returning', 'OrderStatus|returning'), ('returned', 'OrderStatus|returned')], max_length=20, verbose_name='destination status'),
        ),
        migrations.AlterField(
            model_name='orderstatustransition',
            name='src_status',
            field=models.CharField(choices=[('unpaid', 'OrderStatus|unpaid'), ('paid', 'OrderStatus|paid'), ('cancelling', 'OrderStatus|cancelling'), ('cancelled', 'OrderStatus|cancelled'), ('shipping', 'OrderStatus|shipping'), ('done', 'OrderStatus|done'), ('return-requested', 'OrderStatus|return requested'), ('returning', 'OrderStatus|returning'), ('returned', 'OrderStatus|returned')], max_length=20, verbose_name='source status'),
        ),
    ]
