# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20170723_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='shop.Attachment', verbose_name='Product|attachments'),
        ),
    ]
