# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20170801_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rate', 'Coupon|rate'), ('amount', 'Coupon|amount')], default='rate', max_length=10, verbose_name='type')),
                ('price_required', models.FloatField(default=0.0, verbose_name='Coupon|price required')),
                ('discount', models.FloatField(verbose_name='Coupon|discount')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Coupon|is valid')),
            ],
            options={
                'verbose_name': 'coupon',
                'verbose_name_plural': 'coupons',
            },
        ),
    ]
