# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='MILOVE', max_length=100, verbose_name='Coupon|code'),
            preserve_default=False,
        ),
    ]
