# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20170724_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='products/placeholder-120x120.png', upload_to='products', verbose_name='Product|main image'),
        ),
    ]
