# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20170724_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.Category', verbose_name='Product|categories'),
        ),
    ]
