# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20170802_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Address|fullname')),
                ('phone_number', models.CharField(max_length=30, verbose_name='phone number')),
                ('country', models.CharField(choices=[('US', 'United State'), ('CA', 'Canada')], max_length=3, verbose_name='Address|country')),
                ('street_address', models.CharField(max_length=200, verbose_name='Address|street address')),
                ('city', models.CharField(max_length=100, verbose_name='Address|city')),
                ('province', models.CharField(max_length=100, verbose_name='Address|province')),
                ('zip_code', models.CharField(max_length=20, verbose_name='Address|ZIP code')),
            ],
            options={
                'verbose_name': 'billing address',
                'verbose_name_plural': 'billing addresses',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='created datetime')),
                ('amount', models.FloatField(verbose_name='Payment|amount')),
                ('status', models.CharField(choices=[('pending', 'PaymentStatus|pending'), ('closed', 'PaymentStatus|closed'), ('failed', 'PaymentStatus|failed'), ('succeeded', 'PaymentStatus|succeeded')], default='pending', max_length=20, verbose_name='status')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='shop.Order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
            },
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='shop.Payment', verbose_name='payment'),
        ),
    ]
