# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20170802_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_from_balance',
            field=models.FloatField(default=0.0, verbose_name='Payment|amount from balance'),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_from_point',
            field=models.FloatField(default=0.0, verbose_name='Payment|amount from point'),
        ),
        migrations.AddField(
            model_name='payment',
            name='extra_info',
            field=jsonfield.fields.JSONField(blank=True, default={}, verbose_name='extra information'),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(blank=True, choices=[('paypal', 'PayPal'), ('credit-card', 'credit card')], max_length=20, null=True, verbose_name='Payment|method'),
        ),
        migrations.AddField(
            model_name='payment',
            name='point_used',
            field=models.IntegerField(default=0, verbose_name='Payment|point used'),
        ),
        migrations.AddField(
            model_name='payment',
            name='use_balance',
            field=models.BooleanField(default=False, verbose_name='Payment|use balance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='use_point',
            field=models.BooleanField(default=False, verbose_name='Payment|use point'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='vendor_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment|vendor payment ID'),
        ),
    ]
