# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20170725_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='style',
            field=models.CharField(blank=True, max_length=200, verbose_name='Product|style'),
        ),
    ]
