# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20170802_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='shop.Payment', verbose_name='payment'),
        ),
    ]
