# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20170802_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.FloatField(blank=True, default=0.0, verbose_name='paid amount'),
        ),
    ]
