# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_order_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='point_used',
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_amount_from_balance',
            field=models.FloatField(default=0.0, verbose_name='Payment|paid amount from balance'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_point',
            field=models.IntegerField(default=0, verbose_name='Payment|paid point'),
        ),
    ]
