# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import milove.shop.models.goods


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20170725_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='products/placeholder-120x120.png', upload_to=milove.shop.models.goods._prod_image_path, verbose_name='Product|main image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=milove.shop.models.goods._prod_image_path, verbose_name='image'),
        ),
    ]
