# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 11:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20170803_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='created datetime')),
                ('brand', models.CharField(max_length=100, verbose_name='Product|brand')),
                ('category', models.CharField(max_length=30, verbose_name='Product|category')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Product|name')),
                ('size', models.CharField(blank=True, max_length=20, verbose_name='Product|size')),
                ('condition', models.CharField(max_length=50, verbose_name='Product|condition')),
                ('year', models.CharField(max_length=10, verbose_name='SellRequest|year')),
                ('original_price', models.FloatField(verbose_name='Product|original price')),
                ('attachments', models.CharField(max_length=200, verbose_name='Product|attachments')),
                ('description', models.TextField(blank=True, verbose_name='Product|description')),
                ('image_paths', jsonfield.fields.JSONField(blank=True, default=[], verbose_name='image paths')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_requests', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'sell request',
                'verbose_name_plural': 'sell requests',
            },
        ),
    ]
