# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20170725_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_back_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Product|buy back price'),
        ),
    ]
