# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_product_buy_back_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publish_dt',
            field=models.DateTimeField(blank=True, verbose_name='Product|publish datetime'),
        ),
    ]
