# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_sellrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellrequest',
            name='buy_back_price',
            field=models.FloatField(blank=True, null=True, verbose_name='SellRequest|buy back price'),
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='sell_price',
            field=models.FloatField(blank=True, null=True, verbose_name='SellRequest|sell price'),
        ),
        migrations.AlterField(
            model_name='sellrequest',
            name='attachments',
            field=models.CharField(blank=True, max_length=200, verbose_name='Product|attachments'),
        ),
    ]
