# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20170804_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellrequest',
            name='buy_back_price',
        ),
        migrations.RemoveField(
            model_name='sellrequest',
            name='sell_price',
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='buy_back_valuation',
            field=models.FloatField(blank=True, null=True, verbose_name='SellRequest|buy back valuation'),
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='sell_valuation',
            field=models.FloatField(blank=True, null=True, verbose_name='SellRequest|sell valuation'),
        ),
    ]
