# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20170726_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publish_dt',
            field=models.DateTimeField(verbose_name='Product|publish datetime'),
        ),
    ]
