# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20170806_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellrequest',
            name='status',
            field=models.CharField(choices=[('created', 'SellRequest|created'), ('cancelled', 'SellRequest|cancelled'), ('denied', 'SellRequest|denied'), ('valuated', 'SellRequest|valuated'), ('closed', 'SellRequest|closed'), ('decided', 'SellRequest|decided'), ('shipping', 'SellRequest|shipping'), ('authenticating', 'SellRequest|authenticating'), ('selling', 'SellRequest|selling'), ('done', 'SellRequest|done')], default='created', max_length=20, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='valudated_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SellRequest|'),
        ),
    ]
