# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20170806_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellrequest',
            old_name='valudated_dt',
            new_name='valuated_dt',
        ),
    ]
