# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20170726_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(max_length=100, verbose_name='nickname'),
        ),
    ]
