# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20170806_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellrequest',
            name='sell_type',
            field=models.CharField(choices=[('undecided', 'SellRequest|undecided'), ('buy-back', 'SellRequest|buy back'), ('sell', 'SellRequest|sell')], default='undecided', max_length=20, verbose_name='SellRequest|sell type'),
        ),
        migrations.AlterField(
            model_name='sellrequest',
            name='valuated_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SellRequest|valuated datetime'),
        ),
    ]
