# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20170726_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='UserInfo|contact'),
        ),
    ]
