# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20170806_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellrequest',
            name='year',
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='purchase_year',
            field=models.CharField(default=2014, max_length=10, verbose_name='SellRequest|purchase year'),
            preserve_default=False,
        ),
    ]
