# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 02:13
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_userinfo_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='contact',
            field=jsonfield.fields.JSONField(default={}, verbose_name='UserInfo|contact'),
        ),
    ]
