# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20170806_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellrequest',
            name='condition',
            field=models.CharField(max_length=100, verbose_name='Product|condition'),
        ),
    ]
