# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 02:15
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_auto_20170727_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='contact',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True, verbose_name='UserInfo|contact'),
        ),
    ]
