# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import milove.shop.models.product


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_auto_20170806_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellRequestSenderAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Address|fullname')),
                ('phone_number', models.CharField(max_length=30, verbose_name='phone number')),
                ('country', models.CharField(choices=[('US', 'United State'), ('CA', 'Canada')], max_length=3, verbose_name='Address|country')),
                ('street_address', models.CharField(max_length=200, verbose_name='Address|street address')),
                ('city', models.CharField(max_length=100, verbose_name='Address|city')),
                ('province', models.CharField(max_length=100, verbose_name='Address|province')),
                ('zip_code', models.CharField(max_length=20, verbose_name='Address|ZIP code')),
                ('sell_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sender_address', to='shop.SellRequest', verbose_name='sell request')),
            ],
            options={
                'verbose_name': 'sell request sender address',
                'verbose_name_plural': 'sell request sender addresses',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='placeholders/120x120.png', upload_to=milove.shop.models.product._prod_image_path, verbose_name='Product|main image'),
        ),
    ]
