# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 05:23
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_auto_20170727_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='contact',
            field=jsonfield.fields.JSONField(blank=True, default={}, help_text=' ', verbose_name='UserInfo|contact'),
        ),
    ]
