# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_sellrequest_denied_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellrequest',
            name='denied_reason',
            field=models.TextField(blank=True, null=True, verbose_name='SellRequest|denied reason'),
        ),
    ]
