# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_auto_20170807_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellrequest',
            name='shipping_label',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='shipping label'),
        ),
    ]
